[project]
name = "devin-sse-proxy"
version = "0.1.0"
description = "Claude Desktop proxy for Devin MCP over SSE"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9.0",
]
